{
 "title": "REPLACEME_TITLE",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "UUID",
    "label": "UUID",
    "query": "select uuid from requests WHERE $__timeFilter(insertdate);"
   },
   {
    "name": "SITE",
    "label": "SITE",
    "query": "SELECT DISTINCT site FROM (\n    SELECT site1 AS site FROM endtoend.requests\n    UNION ALL\n    SELECT site2 FROM endtoend.requests\n) AS combined_sites;"
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "endtoend",
     "rawSql": "SELECT starttime, updatedate, nextrun FROM endtoend.runnerinfo LIMIT 50 "
    }
   ]
  },
  {
   "title": "Runner Information",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "endtoend",
     "rawSql": "SELECT alive FROM endtoend.runnerinfo LIMIT 50 "
    },
    {
     "dataset": "endtoend",
     "rawSql": "SELECT totalworkers FROM endtoend.runnerinfo LIMIT 50 "
    },
    {
     "dataset": "endtoend",
     "rawSql": "SELECT totalqueue FROM endtoend.runnerinfo LIMIT 50 "
    },
    {
     "dataset": "endtoend",
     "rawSql": "SELECT remainingqueue FROM endtoend.runnerinfo LIMIT 50 "
    },
    {
     "dataset": "endtoend",
     "rawSql": "SELECT lockedrequests FROM endtoend.runnerinfo LIMIT 50 "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "options": {
    "content": "Configuration File: [Github link](https://github.com/sdn-sense/end-to-end-tester/blob/main/packaging/endtoend.yaml)\n\n# Test Process:\n- Generates unique pairs for all valid endpoints (see `entries` key in the configuration file).\n- Runs every 12 hours (or as configured by `runInterval`).\n- Submits a new path request using the template:  \n  - **1Gb Guaranteed Capped**  \n  - **Assign IPv6 address** with both terminal endpoints.\n- If the path request fails, it retries using best effort and records only the best-effort result in the database.\n\n# Timeouts:\n- Defined in the configuration file (e.g., if set to **20 minutes**, creation, validation, and resource activation must complete within this timeframe).\n- Similar constraints apply to cancellation requests.\n\n# Path Creation Scenarios and Workflow (Step by Step):\n\n## **CREATE: Successful and Validated, CANCEL: Successful and Validated**\n- Log information inside database.\n- Remove request from **SENSE-O**.\n\n## **In any of CREATE/CANCEL: Successfully Accepted but Validation Failed**\n- Log information inside database.\n- The entry remains in **SENSE-O** for debugging.\n- The endpoint pair is excluded from future tests until manually deleted.\n\n## **Any Other Failures**\n- **If failure is due to \"Failed to find path\":**  \n  - Log information inside database.  \n  - Remove request from **SENSE-O**, and the pair is retested in the next cycle.\n- **If path creation fails due to other reasons** (e.g., timeout, RM no reply, any other exception):  \n  - Log information inside database.  \n  - The entry remains in **SENSE-O** for debugging.  \n  - The pair is not tested again until deleted from **SENSE-O**.\n\n# Testing Restrictions:\n- As long as an endpoint pair exists in **SENSE-O** and was created by `EndToEndTester`, it is excluded from future tests."
   }
  },
  {
   "title": "Last 7 days (100% Percentage Scaling)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(DATE_FORMAT(insertdate, '%Y-%m-%d %H:00:00')) AS time,\n  SUM(finalstate = 1) * 100.0 / COUNT(*) AS successful,\n  SUM(finalstate = 0 AND pathfindissue = 1) * 100.0 / COUNT(*) AS failed_pathfind,\n  SUM(finalstate = 0 AND pathfindissue = 0) * 100.0 / COUNT(*) AS failed_other\nFROM requests\nWHERE insertdate >= NOW() - INTERVAL 8 DAY\n  AND ($UUID = 'All' OR uuid = ${UUID})\n  AND ($SITE = 'All' OR (site1 = ${SITE} OR site2 = ${SITE}))\nGROUP BY DATE_FORMAT(insertdate, '%Y-%m-%d %H:00:00')\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Last 7 days (Count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(DATE_FORMAT(insertdate, '%Y-%m-%d %H:00:00')) AS time,\n  SUM(finalstate = 1) AS successful,\n  SUM(finalstate = 0 AND pathfindissue = 1) AS failed_pathfind,\n  SUM(finalstate = 0 AND pathfindissue = 0) AS failed_other\nFROM requests\nWHERE insertdate >= NOW() - INTERVAL 8 DAY\n  AND ($UUID = 'All' OR uuid = ${UUID})\n  AND ($SITE = 'All' OR (site1 = ${SITE} OR site2 = ${SITE}))\nGROUP BY DATE_FORMAT(insertdate, '%Y-%m-%d %H:00:00')\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Percentage of Success",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(DATE(insertdate)) AS time,\n  SUM(finalstate = 1) * 100.0 / COUNT(*) AS successful,\n  SUM(finalstate = 0 AND pathfindissue = 1) * 100.0 / COUNT(*) AS failed_pathfind,\n  SUM(finalstate = 0 AND pathfindissue = 0) * 100.0 / COUNT(*) AS failed_other\nFROM requests\nWHERE $__timeFilter(insertdate)\nAND ($UUID = 'All' OR uuid = ${UUID})\nAND ($SITE = 'All' OR (site1 = ${SITE} OR site2 = ${SITE}))\nGROUP BY DATE(insertdate)\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 4, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from requests WHERE $__timeFilter(insertdate) AND ($UUID = 'All' OR uuid = ${UUID}) AND ($SITE = 'All' OR (site1 = ${SITE} OR site2 = ${SITE}));"
    }
   ]
  },
  {
   "title": "Successful requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 7, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from requests WHERE $__timeFilter(insertdate) AND finalstate = 1 AND ($UUID = 'All' OR uuid = ${UUID}) AND ($SITE = 'All' OR (site1 = ${SITE} OR site2 = ${SITE}));"
    }
   ]
  },
  {
   "title": "Failed requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 10, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from requests WHERE $__timeFilter(insertdate) AND finalstate != 1 AND ($UUID = 'All' OR uuid = ${UUID}) AND ($SITE = 'All' OR (site1 = ${SITE} OR site2 = ${SITE}));"
    }
   ]
  },
  {
   "title": "Failed PathFinding",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 13, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from requests WHERE $__timeFilter(insertdate) AND pathfindissue = 1 AND ($UUID = 'All' OR uuid = ${UUID}) AND ($SITE = 'All' OR (site1 = ${SITE} OR site2 = ${SITE}));"
    }
   ]
  },
  {
   "title": "Network Status summary",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "#select count(*) from verification #WHERE $__timeFilter(insertdate) AND ($UUID = 'All' OR uuid = ${UUID}) AND ($SITE = 'All' OR site = ${SITE});\nSELECT COUNT(*) AS count, netstatus FROM verification WHERE $__timeFilter(insertdate) AND ($UUID = 'All' OR uuid = ${UUID}) AND ($SITE = 'All' OR site = ${SITE}) GROUP BY netstatus;"
    }
   ]
  },
  {
   "title": "Verified Summary",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "#select count(*) from verification #WHERE $__timeFilter(insertdate) AND ($UUID = 'All' OR uuid = ${UUID}) AND ($SITE = 'All' OR site = ${SITE});\nSELECT COUNT(*) AS count, CASE WHEN verified = 1 THEN 'True' ELSE 'False' END AS verified FROM verification WHERE $__timeFilter(insertdate) AND ($UUID = 'All' OR uuid = ${UUID}) AND ($SITE = 'All' OR site = ${SITE}) GROUP BY verified;"
    }
   ]
  },
  {
   "title": "All Entries (Requests table)",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "dataset": "endtoend",
     "rawSql": "SELECT insertdate, uuid, site1, site2, finalstate, pathfindissue, requesttype, failure, port1, port2\nFROM endtoend.requests\nWHERE $__timeFilter(insertdate)\n  AND ($UUID = 'All' OR uuid = ${UUID})\n  AND ($SITE = 'All' OR (site1 = ${SITE} OR site2 = ${SITE}))\nLIMIT 1000;"
    }
   ]
  },
  {
   "title": "Success rate (CREATION) Distinct Sites",
   "type": "bargauge",
   "description": "This looks at success rate of creation and path were successful. This show only for endsites. For activation/deactivation - look at Activation chart.",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 58 },
   "targets": [
    {
     "dataset": "endtoend",
     "rawSql": "SELECT\n    site,\n    ROUND((SUM(success_count) * 100.0) / SUM(total_count), 2) AS success_percentage\nFROM (\n    SELECT\n        site1 AS site,\n        SUM(CASE WHEN finalstate = 1 THEN 1 ELSE 0 END) AS success_count,\n        COUNT(*) AS total_count\n    FROM requests\n    WHERE $__timeFilter(insertdate)\n    AND ($UUID = 'All' OR uuid = ${UUID})\n    AND ($SITE = 'All' OR (site1 = ${SITE} OR site2 = ${SITE}))\n    GROUP BY site1\n    UNION ALL\n    SELECT\n        site2 AS site,\n        SUM(CASE WHEN finalstate = 1 THEN 1 ELSE 0 END) AS success_count,\n        COUNT(*) AS total_count\n    FROM requests\n    WHERE $__timeFilter(insertdate)\n    AND ($UUID = 'All' OR uuid = ${UUID})\n    AND ($SITE = 'All' OR (site1 = ${SITE} OR site2 = ${SITE}))\n    GROUP BY site2\n) AS result\nGROUP BY site\nORDER BY success_percentage ASC;"
    }
   ]
  },
  {
   "title": "Guaranteed Capped Requests",
   "type": "stat",
   "description": "This shows what percentage of requests went through with guaranteed capped. The only time it goes to bestEffort - if path finding failed for a to b and 1gb guaranteed capped. ",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    ROUND((COUNT(CASE WHEN requesttype = 'guaranteedCapped' THEN 1 END) * 100.0) / COUNT(*), 2) AS guaranteedCapped_percentage\nFROM requests\nWHERE $__timeFilter(insertdate) AND ($UUID = 'All' OR uuid = ${UUID}) AND ($SITE = 'All' OR (site1 = ${SITE} OR site2 = ${SITE}))\n"
    }
   ]
  },
  {
   "title": "Best Effort Requests",
   "type": "stat",
   "description": "This shows what percentage of requests went through with guaranteed capped. The only time it goes to bestEffort - if path finding failed for a to b and 1gb guaranteed capped. ",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    ROUND((COUNT(CASE WHEN requesttype = 'bestEffort' THEN 1 END) * 100.0) / COUNT(*), 2) AS guaranteedCapped_percentage\nFROM requests\nWHERE $__timeFilter(insertdate) AND ($UUID = 'All' OR uuid = ${UUID}) AND ($SITE = 'All' OR (site1 = ${SITE} OR site2 = ${SITE}))"
    }
   ]
  },
  {
   "title": "Success rate (CREATION) Distinct Sites exclude path find failures",
   "type": "bargauge",
   "description": "This looks at success rate of creation and path were successful. This show only for endsites. For activation/deactivation - look at Activation chart.",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 68 },
   "targets": [
    {
     "dataset": "endtoend",
     "rawSql": "SELECT\n    site,\n    ROUND((SUM(success_count) * 100.0) / SUM(total_count), 2) AS success_percentage\nFROM (\n    SELECT\n        site1 AS site,\n        SUM(CASE WHEN finalstate = 1 THEN 1 ELSE 0 END) AS success_count,\n        COUNT(*) AS total_count\n    FROM requests\n    WHERE $__timeFilter(insertdate)\n    AND ($UUID = 'All' OR uuid = ${UUID})\n    AND ($SITE = 'All' OR (site1 = ${SITE} OR site2 = ${SITE}))\n    AND pathfindissue = 0\n    GROUP BY site1\n    UNION ALL\n    SELECT\n        site2 AS site,\n        SUM(CASE WHEN finalstate = 1 THEN 1 ELSE 0 END) AS success_count,\n        COUNT(*) AS total_count\n    FROM requests\n    WHERE $__timeFilter(insertdate)\n    AND ($UUID = 'All' OR uuid = ${UUID})\n    AND ($SITE = 'All' OR (site1 = ${SITE} OR site2 = ${SITE}))\n    AND pathfindissue = 0\n    GROUP BY site2\n) AS result\nGROUP BY site\nORDER BY success_percentage ASC;"
    }
   ]
  },
  {
   "title": "Guaranteed Capped Requests (exclude path find issue)",
   "type": "stat",
   "description": "This shows what percentage of requests went through with guaranteed capped. The only time it goes to bestEffort - if path finding failed for a to b and 1gb guaranteed capped. ",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    ROUND((COUNT(CASE WHEN requesttype = 'guaranteedCapped' THEN 1 END) * 100.0) / COUNT(*), 2) AS guaranteedCapped_percentage\nFROM requests\nWHERE $__timeFilter(insertdate) AND ($UUID = 'All' OR uuid = ${UUID}) AND ($SITE = 'All' OR (site1 = ${SITE} OR site2 = ${SITE}))\nAND pathfindissue = 0"
    }
   ]
  },
  {
   "title": "Best Effort Requests (exclude path finding issue)",
   "type": "stat",
   "description": "This shows what percentage of requests went through with guaranteed capped. The only time it goes to bestEffort - if path finding failed for a to b and 1gb guaranteed capped. ",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    ROUND((COUNT(CASE WHEN requesttype = 'bestEffort' THEN 1 END) * 100.0) / COUNT(*), 2) AS guaranteedCapped_percentage\nFROM requests\nWHERE $__timeFilter(insertdate) AND ($UUID = 'All' OR uuid = ${UUID}) AND ($SITE = 'All' OR (site1 = ${SITE} OR site2 = ${SITE}))\nAND pathfindissue = 0"
    }
   ]
  },
  {
   "title": "Success rate (CREATION) Site pairs",
   "type": "bargauge",
   "description": "This looks at success rate of creation and path were successful. This show only for endsites. For activation/deactivation - look at Activation chart.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "dataset": "endtoend",
     "rawSql": "SELECT \n    site1, \n    site2, \n    ROUND((SUM(CASE WHEN finalstate = 1 THEN 1 ELSE 0 END) * 100.0) / COUNT(*), 2) AS success_percentage\nFROM requests\nWHERE $__timeFilter(insertdate) AND ($UUID = 'All' OR uuid = ${UUID}) AND ($SITE = 'All' OR (site1 = ${SITE} OR site2 = ${SITE}))\nGROUP BY site1, site2 ORDER BY success_percentage ASC;"
    }
   ]
  },
  {
   "title": "Success rate (CREATION) Site pairs (exclude path finding issue)",
   "type": "bargauge",
   "description": "This looks at success rate of creation and path were successful. This show only for endsites. For activation/deactivation - look at Activation chart.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "endtoend",
     "rawSql": "SELECT \n    site1, \n    site2,\n    ROUND((SUM(CASE WHEN finalstate = 1 THEN 1 ELSE 0 END) * 100.0) / COUNT(*), 2) AS success_percentage\nFROM requests\nWHERE $__timeFilter(insertdate) AND ($UUID = 'All' OR uuid = ${UUID}) AND ($SITE = 'All' OR (site1 = ${SITE} OR site2 = ${SITE}))\nAND pathfindissue = 0\nGROUP BY site1, site2\nORDER BY success_percentage ASC;\n"
    }
   ]
  },
  {
   "title": "Success rate (Activated/Deactivated)",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 98 },
   "targets": [
    {
     "dataset": "endtoend",
     "rawSql": "SELECT \n    site, \n    ROUND((SUM(CASE WHEN netstatus = 'activated' THEN 1 ELSE 0 END) * 100.0) / COUNT(*), 2) AS activated_percentage\nFROM verification\nWHERE $__timeFilter(insertdate) AND ($UUID = 'All' OR uuid = ${UUID}) AND ($SITE = 'All' OR (site = ${SITE} OR site1 = ${SITE} OR site2 = ${SITE}))\nGROUP BY site ORDER BY activated_percentage ASC;"
    }
   ]
  },
  {
   "title": "Verification Entries",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 110 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS count, netstatus, site, site1 as from_site, site2 as to_site, uuid\nFROM verification \nWHERE $__timeFilter(insertdate) AND\n  (${UUID} = 'All' OR uuid = ${UUID}) \nGROUP BY netstatus, site, site1, site2, uuid;"
    }
   ]
  },
  {
   "title": "Verification Entries (grouped by sites)",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 110 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS count, netstatus, site\nFROM verification \nWHERE $__timeFilter(insertdate) AND\n  (${UUID} = 'All' OR uuid = ${UUID}) \nGROUP BY netstatus, site;"
    }
   ]
  },
  {
   "title": "All Entries Grouped by Site Pairs (Requests table)",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 120 },
   "targets": [
    {
     "dataset": "endtoend",
     "rawSql": "SELECT \n    COUNT(*) AS request_count, \n    site1, \n    site2, \n    finalstate,\n    pathfindissue,\n    MIN(uuid) AS sample_uuid, \n    MIN(failure) AS sample_failure, \n    MIN(port1) AS sample_port1, \n    MIN(port2) AS sample_port2\nFROM endtoend.requests\nWHERE $__timeFilter(insertdate)\n  AND ($UUID = 'All' OR uuid = ${UUID})\n  AND ($SITE = 'All' OR (site1 = ${SITE} OR site2 = ${SITE}))\nGROUP BY site1, site2, finalstate, pathfindissue\nLIMIT 1000;"
    }
   ]
  },
  {
   "title": "Request states (last 1000)",
   "type": "table",
   "description": "To see specific request - select UUID or use Filter, time range change",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 134 },
   "targets": [
    {
     "dataset": "endtoend",
     "rawSql": "SELECT *\nFROM endtoend.requeststates\nWHERE $__timeFilter(insertdate)\n  AND ($UUID = 'All' OR uuid = ${UUID})\n  AND ($SITE = 'All' OR (site1 = ${SITE} OR site2 = ${SITE}))\nORDER BY updatedate desc"
    }
   ]
  },
  {
   "title": "Ping Results",
   "type": "table",
   "description": "To see specific request - select UUID or use Filter, time range change",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 148 },
   "targets": [
    {
     "dataset": "endtoend",
     "rawSql": "SELECT *\nFROM endtoend.pingresults\nWHERE $__timeFilter(insertdate)\n  AND ($UUID = 'All' OR uuid = ${UUID})\n  AND ($SITE = 'All' OR (site1 = ${SITE} OR site2 = ${SITE}))\nORDER BY updatedate desc LIMIT 1000"
    }
   ]
  },
  {
   "title": "Locked requests (last 1000)",
   "type": "table",
   "description": "To see specific request - select UUID or use Filter, time range change",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 162 },
   "targets": [
    {
     "dataset": "endtoend",
     "rawSql": "SELECT *\nFROM endtoend.lockedrequests\nWHERE $__timeFilter(insertdate)\n  AND ($UUID = 'All' OR uuid = ${UUID})\n  AND ($SITE = 'All' OR (site1 = ${SITE} OR site2 = ${SITE}))\nORDER BY updatedate desc LIMIT 1000"
    }
   ]
  },
  {
   "title": "Transition times (Time to reach state from previous state)",
   "type": "bargauge",
   "description": "To see specific request - select UUID or use Filter, time range change",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 176 },
   "targets": [
    {
     "dataset": "endtoend",
     "rawSql": "  SELECT \n    rs.state, \n    rs.configstate, \n    rs.action, \n    AVG(rs.totaltime) AS timetoreachstatefromprev\nFROM \n    requeststates rs\nLEFT JOIN stateorder so ON rs.state = so.state AND rs.action = so.action AND rs.configstate = so.configstate\nWHERE $__timeFilter(insertdate)\n  AND ($UUID = 'All' OR uuid = ${UUID})\n  AND ($SITE = 'All' OR (rs.site1 = ${SITE} OR rs.site2 = ${SITE}))\nGROUP BY \n    rs.state, \n    rs.configstate, \n    rs.action\nORDER BY \n  COALESCE(so.orderid, 999);\n"
    }
   ]
  },
  {
   "title": "Transition times (since start, only success)",
   "type": "bargauge",
   "description": "To see specific request - select UUID or use Filter, time range change",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 190 },
   "targets": [
    {
     "rawSql": "  SELECT \n    rs.state, \n    rs.configstate, \n    rs.action, \n    AVG(rs.sincestart) AS timetoreachstatefromprev\nFROM \n    requeststates rs\nLEFT JOIN stateorder so ON rs.state = so.state AND rs.action = so.action AND rs.configstate = so.configstate\nWHERE $__timeFilter(rs.insertdate)\n  AND ($UUID = 'All' OR uuid = ${UUID})\n  AND ($SITE = 'All' OR (rs.site1 = ${SITE} OR rs.site2 = ${SITE}))\n  AND EXISTS (\n        SELECT 1 \n        FROM requests rq \n        WHERE rq.uuid = rs.uuid \n          AND rq.finalstate = 1\n    )\nGROUP BY \n    rs.state, \n    rs.configstate, \n    rs.action\nORDER BY \n  COALESCE(so.orderid, 999);\n"
    }
   ]
  },
  {
   "title": "Transition times (only final status, only successful)",
   "type": "bargauge",
   "description": "To see specific request - select UUID or use Filter, time range change",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 204 },
   "targets": [
    {
     "rawSql": "SELECT \n    rs.state, \n    rs.configstate, \n    rs.action, \n    AVG(rs.sincestart) AS timetoreachstatefromprev\nFROM \n    requeststates rs\nLEFT JOIN \n    stateorder so ON rs.state = so.state \n                 AND rs.action = so.action \n                 AND rs.configstate = so.configstate\nWHERE \n    $__timeFilter(rs.insertdate)\n    AND ($UUID = 'All' OR rs.uuid = ${UUID})\n    AND ($SITE = 'All' OR (rs.site1 = ${SITE} OR rs.site2 = ${SITE}))\n    AND EXISTS (\n        SELECT 1 \n        FROM requests rq \n        WHERE rq.uuid = rs.uuid \n          AND rq.finalstate = 1\n          AND (\n              (rs.state = 'CREATE - READY' AND rs.configstate = 'STABLE' AND rs.action = 'create') OR\n              (rs.state = 'MODIFY - READY' AND rs.configstate = 'STABLE' AND rs.action = 'modifycreate') OR\n              (rs.state = 'CANCEL - READY' AND rs.configstate = 'STABLE' AND rs.action = 'cancelrep') OR\n              (rs.state = 'REINSTATE - READY' AND rs.configstate = 'STABLE' AND rs.action = 'reprovision') OR\n              (rs.state = 'MODIFY - READY' AND rs.configstate = 'STABLE' AND rs.action = 'modify') OR\n              (rs.state = 'CANCEL - READY' AND rs.configstate = 'STABLE' AND rs.action = 'cancel')\n          )\n    )\nGROUP BY \n    rs.state, \n    rs.configstate, \n    rs.action\nORDER BY \n  COALESCE(so.orderid, 999);"
    }
   ]
  }
 ]
}